TFNO:
  n_modes: 16
  hidden_channels: 32
  projection_channels: 64
  factorization: 'tucker'
  rank: 0.42

adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [150,500]
    gamma: 0.1

train:
  epochs: 1000
  batch_size: 2

data:
  outputs : [U]
  encode_input: False
  encode_output: True
  positional_encoding: True
  grid_boundaries: [[0.0, 1.0], [0.0, 1.0]]