TFNO:
  n_modes: 16
  hidden_channels: 32
  projection_channels: 64
  factorization: 'tucker'
  rank: 0.42

adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [150,500]
    gamma: 0.1

train:
  epochs: 2
  batch_size: 64

multi_resolution: True

data_format:
  encode_input: True
  encode_output: True
  positional_encoding: True
  grid_boundaries: [[-1.0, 1.0], [-1.0, 1.0]]

data_source:
  name: rans
  train_args:
    outputs: [U]
    horizontal_grid_spacing: [0.5,1.0,2.0]
    # inflow_wind_direction : [270.0, 275.0, 280.0, 285.0, 290.0, 295.0, 300.0, 305.0, 310.0, 315.0]
    inflow_wind_direction : [270.0, 273.0, 276.0, 279.0, 282.0, 285.0, 288.0, 291.0, 294.0, 297.0,
                            300.0, 303.0, 306.0, 309.0, 312.0, 315.0]
  test_args:
    outputs: [U]
    horizontal_grid_spacing: [4.0]
    # inflow_wind_direction : [270.0, 275.0, 280.0, 285.0, 290.0, 295.0, 300.0, 305.0, 310.0, 315.0]
    inflow_wind_direction : [270.0, 273.0, 276.0, 279.0, 282.0, 285.0, 288.0, 291.0, 294.0, 297.0,
                            300.0, 303.0, 306.0, 309.0, 312.0, 315.0]
  evaluate_args:
    output_names: [U]
    plot : True