TFNO:
  n_modes: 16
  hidden_channels: 32
  projection_channels: 64
  factorization: 'tucker'
  rank: 0.42

adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [150,500]
    gamma: 0.1

train:
  epochs: 1000
  batch_size: 8

data_format:
  encode_input: False
  encode_output: True
  positional_encoding: True
  grid_boundaries: [[-1.0, 1.0], [-1.0, 1.0]]

data_source:
  name: rans
  train_args:
    outputs: [U]
    horizontal_grid_spacing: [1.0]
    inflow_wind_direction : [270.0, 275.0, 280.0, 285.0, 290.0, 295.0, 300.0, 305.0, 310.0, 315.0]
  test_args:
    outputs: [U]
    horizontal_grid_spacing: [2.0]
    inflow_wind_direction : [270.0, 275.0, 280.0, 285.0, 290.0, 295.0, 300.0, 305.0, 310.0, 315.0]
  evaluate_args:
    output_names: [U]
    plot : True