defaults:
  - _self_
  - override hydra/sweeper: optuna
TFNO:
  n_modes: [32,32]
  hidden_channels: 32
  lifting_channels: 256
  projection_channels: 32
  n_layers: 4
  use_mlp: True
  preactivation: True
  fno_skip: 'soft-gating'
  factorization: 'tucker'
  rank: 0.85
  joint_factorization: True


adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [150,500,1000]
    gamma: 0.1

train:
  epochs: 2000
  batch_size: 256
  test_batch_size: 100
  loss: l2
  # test_loss: [l2,h1]
  test_loss:  [l2]

multi_resolution: False

data_format:
  encode_input: True
  encode_output: True
  positional_encoding: True
  grid_boundaries: [[-1.0, 1.0], [-1.0, 1.0]]

data_source:
  name: rans
  train_args:
    outputs: [U]
    horizontal_grid_spacing: [2.0]
    # inflow_wind_direction : [270.0, 290.0, 310.0]
    inflow_wind_direction : [270.0, 273.0, 276.0, 279.0, 282.0, 285.0, 288.0, 291.0, 294.0, 297.0,
                            300.0, 303.0, 306.0, 309.0, 312.0, 315.0]
  test_args:
    outputs: [U]
    horizontal_grid_spacing: [4.0]
    # inflow_wind_direction : [270.0, 290.0, 310.0]
    inflow_wind_direction : [270.0, 273.0, 276.0, 279.0, 282.0, 285.0, 288.0, 291.0, 294.0, 297.0,
                            300.0, 303.0, 306.0, 309.0, 312.0, 315.0]
  evaluate_args:
    output_names: [U]
    plot : True

hydra:
  mode : MULTIRUN
  sweeper:
    n_trials: 12
    params:
      data_format.encode_input: choice(True, False)
      data_format.encode_output: choice(True, False)
      data_format.positional_encoding: choice(True, False)
      TFNO.n_modes: choice([16,16], [32,32], [48,48])
