defaults:
  - _self_
  - override hydra/sweeper: optuna
TFNO:
  n_modes: [12,12]
  hidden_channels: 16
  lifting_channels: 256
  projection_channels: 32
  n_layers: 4
  use_mlp: False
  preactivation: False
  fno_skip: 'linear'
  factorization: 'tucker'
  rank: 0.85
  joint_factorization: False
  domain_padding: None


adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [150,500,1000]
    gamma: 0.1

train:
  epochs: 2000
  batch_size: 256

data_format:
  encode_input: True
  encode_output: True
  positional_encoding: True
  grid_boundaries: [[0.0, 1.0], [0.0, 1.0]]

data_source:
  name: synthetic_data
  train_args:
    resolution: 64
    multivariate: false
    reduce: 0.1
  test_args:
    resolution: 128
    multivariate: false
  evaluate_args:
    output_names: [V]
    plot : True
multi_resolution: False
hydra:
  mode : MULTIRUN
  sweeper:
    n_trials: 50
    params:
      TFNO.lifting_channels: range(64, 256, 64)
      TFNO.n_layers: choice(3,4,5)
      TFNO.use_mlp: choice(True, False)
      TFNO.preactivation: choice(True, False)
      TFNO.fno_skip: choice('linear', 'identity', 'soft-gating')
      TFNO.joint_factorization: choice(True, False)
      
      