TFNO:
  n_modes: 16
  hidden_channels: 32
  projection_channels: 64
  factorization: 'tucker'
  rank: 0.42

adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [150,500,800]
    gamma: 0.1

train:
  epochs: 1000
  batch_size: 64

data_format:
  encode_input: True
  encode_output: False
  positional_encoding: True
  grid_boundaries: [[0.0, 1.0], [0.0, 1.0]]

data_source:
  name: synthetic_data
  train_args:
    resolution: 64
    multivariate: false
  test_args:
    resolution: 128
    multivariate: false
  evaluate_args:
    output_names: [V]
    plot : True