TFNO:
  n_modes: 16
  hidden_channels: 32
  projection_channels: 64
  factorization: 'tucker'
  rank: 0.42

adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [150,500]
    gamma: 0.1

train:
  epochs: 3
  batch_size: 64

data_format:
  encode_input: False
  encode_output: False
  positional_encoding: True
  grid_boundaries: [[0.0, 1.0], [0.0, 1.0]]

data_source:
  name: synthetic_data
  train_args:
    resolution: 32
  test_args:
    resolution: 64
  evaluate_args:
    output_names: [U,V,W]
    plot : True