defaults:
  - _self_
  # - override hydra/sweeper: optuna
TFNO:
  n_modes: [12,12]
  hidden_channels: 24
  lifting_channels: 256
  projection_channels: 32
  n_layers: 4
  use_mlp: True
  preactivation: True
  fno_skip: 'linear'
  factorization: 'tucker'
  rank: 0.85
  joint_factorization: True

adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [100,200,300,400,500,750]
    gamma: 0.5

train:
  epochs: 1000
  batch_size: 256
  test_batch_size: 250
  loss: l2
  # test_loss: [l2,h1]
  test_loss:  [l2]

data_format:
  encode_input: True
  encode_output: True
  positional_encoding: True
  grid_boundaries: [[0.0, 1.0], [0.0, 1.0]]

data_source:
  name: synthetic_data
  train_args:
    resolution: 64
    multivariate: false
    reduce: 0.1
  test_args:
    resolution: 128
    multivariate: false
  evaluate_args:
    output_names: [V]
    plot : True
multi_resolution: False
hydra:
  mode : MULTIRUN
  sweeper:
    # n_trials: 50
    params:
      train.epochs: choice(500,750,1000,10000)

      