TFNO:
  n_modes: [32,32]
  hidden_channels: 32
  # lifting_channels: 4
  # projection_channels: 4
  n_layers: 12
  use_mlp: True
  preactivation: True
  fno_skip: 'soft-gating'
  factorization: 'tucker'
  rank: 0.85
  joint_factorization: True
  non_linearity : tanh #gelu # use same capitalisation as torch.nn.functional

adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [50,100,150,200,250,500]
    gamma: 0.5

train:
  epochs: 500
  batch_size: 64
  test_batch_size: 25
  loss: weightedL2
  test_loss: [l2,h1]
  # test_loss:  [l2]
  loss_weighting_function: [linear_legacy]

super_resolution: False
multi_resolution: 
  mode: batch_wise # i.e. Epoch - Batch - Resolution
  # mode: epoch_wise # i.e. Epoch - Resolution - Batch
  # mode: resolution_wise # i.e. Resolution - Epoch - Batch
  shuffle : False

skip_errors: False

data_format:
  encode_input: False
  encode_output: False
  use_rans_encoder: False # if encode output is false this will not be accessed
  positional_encoding: False
  grid_boundaries: [[-1.0, 1.0], [-1.0, 1.0]]
  MGPatching: 
    use: False
    kwargs:
      padding_fraction: 0.078125
      stitching: True
      levels: 1

data_source:
  name: rans
  train_args:
    inputs: [Fx]
    outputs: [U]
    path: data/RANS_Newton/
    horizontal_grid_spacing: [0.5,1.0,2.0]
    inflow_wind_direction : [270.0, 273.0, 276.0, 279.0, 282.0, 285.0, 288.0, 291.0, 294.0, 297.0,
                            300.0, 303.0, 306.0, 309.0, 312.0, 315.0]
  test_args:
    horizontal_grid_spacing: [4.0]

  evaluate_args:
    output_names: [U]
    relative_position_cross_section : 0.95
    plot : True