TFNO:
  n_modes: [32,32]
  hidden_channels: 32
  # lifting_channels: 4
  # projection_channels: 4
  n_layers: 4
  use_mlp: True
  preactivation: True
  fno_skip: 'soft-gating'
  factorization: 'tucker'
  rank: 0.85
  joint_factorization: True

adam:
  lr: 0.01
  weight_decay: 0.00001

scheduler:
  name : MultiStepLR
  args:
    milestones: [125,250,500]
    gamma: 0.1

train:
  epochs: 1000
  batch_size: 256
  test_batch_size: 50
  loss: h1
  test_loss: [l2,h1]
  # test_loss:  [l2]

super_resolution: False
multi_resolution: False
skip_errors: False

data_format:
  encode_input: False
  encode_output: False
  use_rans_encoder: False # if encode output is false this will not be accessed
  positional_encoding: False
  grid_boundaries: [[-1.0, 1.0], [-1.0, 1.0]]
  MGPatching: 
    use: False
    kwargs:
      padding_fraction: 0.078125
      stitching: True
      levels: 1

data_source:
  name: rans
  train_args:
    outputs: [U]
    horizontal_grid_spacing: [2.0]
    # inflow_wind_direction : [270.0, 290.0, 310.0] 
    inflow_wind_direction : [270.0, 273.0, 276.0, 279.0, 282.0, 285.0, 288.0, 291.0, 294.0, 297.0,
                            300.0, 303.0, 306.0, 309.0, 312.0, 315.0]
  test_args:
    outputs: [U]
    horizontal_grid_spacing: [4.0]
    # inflow_wind_direction : [270.0, 290.0, 310.0]
    inflow_wind_direction : [270.0, 273.0, 276.0, 279.0, 282.0, 285.0, 288.0, 291.0, 294.0, 297.0,
                            300.0, 303.0, 306.0, 309.0, 312.0, 315.0]
  evaluate_args:
    output_names: [U]
    plot : True