defaults:
  - base
  - _self_
### OVVERRIDES
skip_errors: True

data_source:
  train_args:
    inputs: [Fx]
    outputs: [U]
    path: data/RANS_Newton/
    horizontal_grid_spacing: [0.5,1.0,2.0]
  test_args:
    horizontal_grid_spacing: [4.0]

multi_resolution: True

TFNO : 
  non_linearity : tanh #gelu # use same capitalisation as torch.nn.functional

scheduler:
  name : MultiStepLR
  args:
    milestones: [50,100,150,200,250,300]
    gamma: 0.5

train:
  epochs: 250
  batch_size: 64
  test_batch_size: 25
  loss: weightedL2
  test_loss: [l2,h1,weightedL2]
  loss_weighting_function: [linear_legacy]
  # test_loss:  [l2]


###
hydra:
  mode : MULTIRUN
  sweeper:
    params:
      TFNO.rank: choice(0.5, 0.7, 0.9)
      TFNO.use_mlp: choice(True, False)
      TFNO.preactivation: choice(True, False)
      TFNO.fno_skip: choice('soft-gating', 'linear', 'identity')
      
      

