defaults:
  - base
  - _self_
### OVVERRIDES
skip_errors: True

data_source:
  train_args:
    inputs: [Fx]
    path: data/RANS_Newton/
    horizontal_grid_spacing: [0.5,1.0,2.0]
  test_args:
    horizontal_grid_spacing: [4.0]

multi_resolution: True

TFNO : 
  non_linearity : tanh #gelu # use same capitalisation as torch.nn.functional

scheduler:
  name : MultiStepLR
  args:
    milestones: [50,100,200,400,800]
    gamma: 0.5

train:
  epochs: 1200
  batch_size: 64
  test_batch_size: 25
  loss: weightedL2
  test_loss: [l2,h1,weightedL2]
  # test_loss:  [l2]


###
hydra:
  mode : MULTIRUN
  sweeper:
    params:
      train.loss_weighting_function: choice([linear],[axial_bump],[center_sink], 
                                            [linear,axial_bump],[linear,center_sink],
                                            [axial_bump,center_sink],
                                            [linear,axial_bump,center_sink],[],[linear_legacy])
