defaults:
  - base
  - _self_
TFNO:
  n_modes: [4,4]
  hidden_channels: 4
  lifting_channels: 4
  projection_channels: 4
  n_layers: 4
  use_mlp: True
  preactivation: True
  fno_skip: 'soft-gating'
  factorization: 'tucker'
  rank: 0.85
  joint_factorization: True

train:
  epochs: 1
  batch_size: 25
  test_batch_size: 50
  loss: weightedL2
  loss_weighting_function : [linear_legacy]
  test_loss: [l2,h1]

data_source:
  train_args:
    horizontal_grid_spacing: [0.5,1.0]
    inflow_wind_direction: [270.0, 290.0, 310.0]
  test_args:
    horizontal_grid_spacing: [2.0]
    inflow_wind_direction: [270.0, 290.0, 310.0]

multi_resolution: 
  mode: batch_wise # i.e. Epoch - Batch - Resolution
  # mode: epoch_wise # i.e. Epoch - Resolution - Batch
  # mode: resolution_wise # i.e. Resolution - Epoch - Batch
  shuffle : False

