defaults:
  - base
  - _self_
  - override hydra/sweeper: optuna
### OVVERRIDES
skip_errors: True

data_source:
  train_args:
    inputs: [Fx]
    outputs: [U]
    path: data/RANS_Newton/
    horizontal_grid_spacing: [0.5,1.0,2.0]
  test_args:
    horizontal_grid_spacing: [4.0]

multi_resolution: True

TFNO : 
  non_linearity : tanh #gelu # use same capitalisation as torch.nn.functional

scheduler:
  name : MultiStepLR
  args:
    milestones: [50,100,150,200,250,300]
    gamma: 0.5

train:
  epochs: 250
  batch_size: 32
  test_batch_size: 25
  loss: weightedL2
  test_loss: [l2]
  loss_weighting_function: [linear_legacy]

###
hydra:
  mode : MULTIRUN
  sweeper:
    n_trials: 40
    params:
      TFNO.n_layers: range(8,20,2)
      TFNO.hidden_channels: range(24,80,8)
      TFNO.rank: range(0.4, 1.0, 0.05)
      TFNO.n_modes: choice([32,32],[48,48],[64,64])
